### PR TITLE
Additional IIS WebService 

### PR DESCRIPTION
**Pull request by BobSilent**
Extracted a Core Implementation, which is independent of any hosting
added an IIS WebApi Implementation
The WebApi Implementation uses swagger to document the online api: `http://YOUR_SERVER:PORT/swagger`

the configuration is stored in the Web.Config
```
    <VsGallerySettings>
        <Storage VsixStorageDirectory="~/App_Data/VsixStorage" UploadDirectory="~/App_Data/VsixUploads" />
        <Gallery Guid="54F7969C-F561-4B16-9D6B-7325EDE0A3C1" Title="Super Productive Gallery" TrackDownloads="True" TrackRatings="True" />
    </VsGallerySettings>
```
similar to the config.ini
The Hosting and the Service Configuration is done in the config as well, but in the default sections available.

to bring the configuration into the app.config for the vsgallery.exe implementation would be quite easy, but as you said you want to stick with the easier (or leightweight ini descrption) instead of the app.config xml syntax i did not change it.
But having an ini configuration for the webservice, where everything is already in appconfig did not make sense.

Btw. UploadMaxFileSize=10MB is never used?!
whereas the Upload file size for IIS Hosting is configured here (default location - **maxRequestLength**): 
`<httpRuntime targetFramework="4.6.1" maxRequestLength="20480" />`

### CODE REVIEW

**Comment by sverrirs** [comment]
Wow, this looks great :+1: . Give me a little time to properly test this on my end before I merge these changes into master.

Re the INI file, I honestly don't mind having an XML file instead, the only thing I like is for the configuration to still be relatively straight forward for the stand-alone version of this app :)

**Comment by sverrirs** [comment]
Hmm.. I keep getting a System.StackOverflowException whenever I start the VSGallery project. The exception happens when the code registers the first Nancy Route (i.e. the FeedModule). 

Edit: This is caused by a circular reference in the VsGallery.Core.IStorageConfiguration somewhere

**Comment by BobSilent** [comment]
Just take the time needed, if you find something just send me a mail or write in the pull request.

Afterwards I can make a proposal for the config.ini in app.config
It would follow the web config in web Service

It was quite easy because it was a simple and good structured implementation by you. The only thing missing are some automated unit tests yet.😉

Have a nice weekend 😀


-------- Original Message --------

**Comment by BobSilent** [comment]
Ok, I will check on my site... Maybe it was too late yesterday 😉


-------- Original Message --------

**Comment by BobSilent** [comment]
was a merge issue during rebase and squashing the commits:
`vsgallery/Webserver/SelfHostBootstrapper.cs`

there was a missing container registration for the dependency injection
`container.Register<IStorageConfiguration>(_configuration.Storage).WithStrongReference();`

strange that this leads to a stackoverflow exception and not to a better, more detailed exception that no implementation can be found for dependency injection. But thats Nancy... ;)

**Comment by sverrirs** [comment]
Ah yeah, I knew it had to be something simple, thanks for fixing this so fast. 
Indeed, I am not too fond of the TinyIoC container used by Nancy, a little bit too "intelligent" at times.

**Comment by sverrirs** [comment]
Could I ask you a favor?  I was going to fix up the readme a little bit to better support installation and configuration (the readme is pretty bare bones at the moment and quite technical), could I ask you to document the IIS part? E.g. Installation and configuration of the components and possible dependencies and requirements for the running environment?

And you're right about the testing being missing, I guess with this addition I can't skirt around adding a travis build anymore as well.

**Comment by BobSilent** [comment]
Sure I can do this, do you think it might make sense to split up the readme in just the "marketing" parts and add additional technical documentation for e.g. setup and configuration of iis, the web API.

Do you create a branch for updating the documentary​?
Or do you work on master and I send you a PR?


-------- Original Message --------

**Comment by sverrirs** [comment]
Excellent, glad to hear it :)

I think it is a good idea to split the readme up into a "marketing"/"intro" readme and then have separate ones for the technical parts (perhaps three technical parts, one describing the HTTP API as it exists now in the readme and then one for configuring the standalone Nancy microservice and one for IIS configuring). 

Making the changes in master is fine for now, so doing this via PRs sounds like a good plan :)

**Pull request merged**
